### ISSUE TITLE
is this the correct SSD1306 to BBB wiring?

### ISSUE THREAD

**Issue by tnishimura** [TJC/BeagleBone#1]
Hi,
Just to make sure, is this the correct wiring for an adafruit 128x32 spi oled SSD1306 lcd to a Beagle Bone Black?  And should there be any resistors or anything?

```
LCD Pin  BBB Pin  Pin Mode  Mode Name 

CS       P9_17    mode 0    spi0_cs0 
CLK      P9_22    mode 0    spi0_sclk 
DATA     P9_21    mode 0    spi0_d0   (master->slave)
VIN      P9_03 
GND      P9_01
RST      any digital output specified by constructor
D/C      any digital output specified by constructor
```

**Comment by TJC** [comment]
I'll have to double check my board when I get home, but that sounds about right. I'm using the same adafruit LCD as that.
I didn't add any resistors myself and it's been fine.

However I haven't managed to get the code working on the BB Black myself; there's a new way of telling the kernel about pin muxing on it, and all the code in my library is based on the old method. (And when I tried using device-tree overlays on my beaglebone, it just segfaulted the kernel a lot)
